# Generated by Django 3.0 on 2019-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='reviews',
            field=models.IntegerField(null=True),
        ),
    ]
